### ISSUE TITLE
Should we move discussion of open science/licensing/hosting to a new repo?

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/site#917] opened 2015-04-05 16:03 UTC
The discussion of open science, licensing, and hosting is the same in the Git and Mercurial lessons.  Should we move it into a short lesson of its own?

**Comment by wking** [comment] 2015-04-05 16:34
On Sun, Apr 05, 2015 at 09:03:54AM -0700, Greg Wilson wrote:
> The discussion of open science, licensing, and hosting is the same
> in the Git and Mercurial lessons.  Should we move it into a short
> lesson of its own?

Hosting is probably a bit different (no Mercurial on GitHub anyway).
But I'm in favor of pulling out the open science and licensing
discussions into their own lesson.  And if we want to pull out some
generic hosting info and leave it to the tool-specific lessons to just
list out possible hosting sites, I'm fine with that too.

**Comment by xuf12** [comment] 2015-04-05 18:17
I like the idea of moving open science and licensing into a short new lesson. We didn't have time to go over the "open science" section in 2 of our recent workshops, and I think it merits a different emphasis and perhaps teaching style (if we do it at the end of the Git lesson, we are switching people from typing to listening). The concept of hosting flows naturally with open science and licensing and a generic hosting section would be good. I agree with @wking that we can leave the tool-specific hosting part in their own lessons.

**Comment by iglpdc** [comment] 2015-04-05 18:49
I'm also in favor of making a new lesson with the open science materials. Now that the SWC core has being downsized to three topics, some workshops may have an extra half-day, perfect to covering things like this. 

In all my workshops, I've never seen the open science materials covered in the version control lesson: simply, teaching Git takes the whole half-day. Splitting this into a new lesson would be more realistic with our proposed schedule.

I don't think that we need to cover hosting in the version control lesson, even if it's tool-dependent. The instructor can mention it briefly, and refer to the learners to the open science lesson, which doesn't have many technical complications preventing our novice learners to study it on their own.

**Comment by wking** [comment] 2015-04-05 19:29
On Sun, Apr 05, 2015 at 11:49:31AM -0700, Ivan Gonzalez wrote:
> … The instructor can mention it briefly, and refer to the learners
> to the open science lesson, which doesn't have many technical
> complications preventing our novice learners to study it on their
> own.

It may not be technical in a software/electronics bent, but I think
the license distinction (copyleft or not, software or not, …) is
likely to be confusing enough that it's worth spending some face time
on it (time permitting).  Also, punting on licensing makes it feel
less important, and I don't want to implicitly reinforce the
“licensing doesn't matter” viewpoint held by ~80% of GitHub
repositories [1].

[1]: https://github.com/blog/1964-open-source-license-usage-on-github-com

**Comment by justbennet** [comment] 2015-04-05 19:55
I think both topics would benefit from not being the tail of some other lesson.

It might be interesting and informative to explain exactly how and why open software and open science are related and how they are very different from each other.  At some level, they may be primarily related because of the presence of the word 'open', but perhaps there are more differences in what they are than their accompanying each other sometimes suggests....

Part of my day job is to review the terms of software licenses, open and otherwise, and I've run across some surprising things in the last few years.  That is particularly the case if the research part of people's activities overlaps with anything clinical.  It may also be worth mentioning that some institutions have implicit (or explicit) rights to what gets written and/or done on their dime that can also be surprising.

That's my ha'penny.

**Comment by cryptarch** [comment] 2015-04-05 20:05
Agreed. Licensing deals with a different set of concepts and always felt like a bit of an appendix to the main Git materials. One could argue that open source licensing goes hand in hand with code collaboration, especially on GitHub, but you could say the same thing about lots of other topics that aren't included in the Git lesson. At the end of the day, licensing is not essential to using Git. Certainly less essential than branching and merging, which are also excluded from the novice materials.

However, if "open things" (software, science) are put in a new lesson, I do wonder when will they be taught? There isn't more time at the existing two day bootcamps for a new lesson.

**Comment by wking** [comment] 2015-04-05 20:13
On Sun, Apr 05, 2015 at 01:05:41PM -0700, Timothy Rice wrote:
> At the end of the day, licensing is not essential to using
> Git.

Agreed.  And having an all-rights-reseved repository that's open to
the public on GitHub is certainly better then understanding licensing
but *not* having a repository somewhere public ;).  When reviewing
someone else's science, I'd rather have read-only access to their
material than no access at all.

**Comment by douglatornell** [comment] 2015-04-05 20:54
Splitting the open science/licensing/hosting content out of the version control lessons works for me. I generally refer the learners to that piece of the material that they should read on their own because it is more of an essay than most of the other materials. I also often discuss licensing and hosting with learners in breaks or after the workshop but that may be due to special circumstances:
 1. Most workshops that I help instructor are close to home so I (or people whose knowledge of open science/licensing/hosting I have influenced) have interaction with the learners on an ongoing basis after the workshops.
 2. I teach version control immediately after shell on day 1 so there is more time for it an related issues to sink in and be discussed during the workshop. (That's not why I teach it on day 1, just a consequence of doing so.)

**Comment by gvwilson** [comment] 2015-04-06 00:29
I usually hold the open lesson in reserve: if people are really getting 
version control, we spend the whole morning on that.  If they're 
struggling/frustrated, I stop half an hour early and give them the open 
lesson.

**Comment by ctb** [comment] 2015-04-06 11:51
A big -1 from me; to drive adoption, this needs to be worked into existing material, with pointers to more in depth material and discussion.  Otherwise it will simply be skipped by many.

(This is assuming one of the goals of Software Carpentry is to push open science ;).

**Comment by wking** [comment] 2015-04-06 16:05
On Mon, Apr 06, 2015 at 04:51:46AM -0700, C. Titus Brown wrote:
> A big -1 from me; to drive adoption, this needs to be worked into
> existing material…
> …
> (This is assuming one of the goals of Software Carpentry is to push
> open science ;).

Couldn't we achieve this same goal by factoring it out into its own
lesson and then adding the new lesson to our list of those required to
get a SWC label [1]?

And clearly one of our goals is to push using open tools to do
science, but I'm personally not clear on whether that officialy
extends to pushing for the science itself to be open.  Personally, I
think it's better to have open science, but there are lots of folks
doing closed-source work on top of open-source tools, and SWC's use of
CC BY instead of BY-SA seems to lean in the more permissive direction.

[1]: http://software-carpentry.org/blog/2015/03/and-now-we-are-three.html

**Comment by ctb** [comment] 2015-04-06 21:36
On Mon, Apr 06, 2015 at 09:05:53AM -0700, W. Trevor King wrote:
> On Mon, Apr 06, 2015 at 04:51:46AM -0700, C. Titus Brown wrote:
> > A big -1 from me; to drive adoption, this needs to be worked into
> > existing material???
> > ???
> > (This is assuming one of the goals of Software Carpentry is to push
> > open science ;).
> 
> Couldn't we achieve this same goal by factoring it out into its own
> lesson and then adding the new lesson to our list of those required to
> get a SWC label [1]?

No, I don't think so; separate lessons divorced from use cases are not
as persuasive.

And yes, I do have an agenda.

**Comment by iglpdc** [comment] 2015-04-06 22:15
But the problem is the timing. The fact is that the git lesson takes over 3 hours without the open science part, so most instructors aren't able to finish it on time. In the current schedule, we cheat, pretending we'll cover it all in one morning. This leads to frustration in both learners and instructors, because they don't meet the expectations. In the rush, the open science materials are often skipped. If we want to keep everything in one lesson, we have to be realistic and schedule more time for it.

**Comment by wking** [comment] 2015-04-06 22:33
On Mon, Apr 06, 2015 at 02:36:54PM -0700, C. Titus Brown wrote:
> Mon, Apr 06, 2015 at 09:05:53AM -0700, W. Trevor King:
> > Mon, Apr 06, 2015 at 04:51:46AM -0700, C. Titus Brown:
> > > A big -1 from me; to drive adoption, this needs to be worked
> > > into existing material…
> > > …
> > > (This is assuming one of the goals of Software Carpentry is to
> > > push open science ;).
> >
> > Couldn't we achieve this same goal by factoring it out into its
> > own lesson and then adding the new lesson to our list of those
> > required to get a SWC label [1]?
> 
> No, I don't think so; separate lessons divorced from use cases are
> not as persuasive.

I don't actually see anything in [1] that would need to be dropped if
we pulled this out into its own lesson.  If we pull out the hosting
material with the licensing and open-science stuff, then Mercurial
users get an extra word to read, but that's not a big deal.  Either
way, I don't see the text getting less persuasive.  On the other hand,
the use cases in the current material are “Software Carpentry uses …”.
Maybe it would be harder to attach examples after pulling the content
out into its own lesson (I currently skeptical but open to
convincing), but as it stands I don't see a pedagogical cost.

> And yes, I do have an agenda.

I also have an open-science agenda.  I just don't know if pushing open
science is a SWC agenda, or if it's an optional agenda for the
individual members.

[1]: https://github.com/swcarpentry/git-novice/blob/7e9646d50b5d24a6ff9a80a844f4167a8d0272b5/08-open.md

**Comment by wking** [comment] 2015-04-06 22:35
On Mon, Apr 06, 2015 at 03:15:14PM -0700, Ivan Gonzalez wrote:
> But the problem is the timing…

I think timing concerns are orthogonal to pulling this out into a new
lesson.  If you want to cover this material, you'll need
accurate-enough time estimates in your schedule regardless of which
content is maintained in which repository.

**Comment by gvwilson** [comment] 2015-04-06 23:01
We dropped SQL as a mandatory topic; I'd be keen to suggest putting a 
short lesson on open science into the core in its place, so that we're 
sure this *has* to be taught.

**Comment by wking** [comment] 2015-04-06 23:10
On Mon, Apr 06, 2015 at 04:01:12PM -0700, Greg Wilson wrote:
> We dropped SQL as a mandatory topic; I'd be keen to suggest putting
> a short lesson on open science into the core in its place, so that
> we're sure this *has* to be taught.

I'm fine with this (I'm also fine with not requiring it ;), but I feel
like we dropped SQL because lots of folks were already replacing it
with alternative content [1].  That means folks will no longer have
time (or as much time) to cover one of the alternative lessons
(testing, debugging, Make, …) as they do now, without dropping the SWC
label.  If we want to pitch a smaller tent, we should have a guess at
how many potentially SWC-branded workshops will turn into unbranded
workshops as a result.

[1]: http://software-carpentry.org/blog/2015/03/and-now-we-are-three.html

**Comment by padraic7a** [comment] 2015-04-07 09:03
I support the idea of moving it to it's own lesson.

**Comment by ctb** [comment] 2015-04-08 11:05
On Mon, Apr 06, 2015 at 04:10:49PM -0700, W. Trevor King wrote:
> On Mon, Apr 06, 2015 at 04:01:12PM -0700, Greg Wilson wrote:
> > We dropped SQL as a mandatory topic; I'd be keen to suggest putting
> > a short lesson on open science into the core in its place, so that
> > we're sure this *has* to be taught.
> 
> I'm fine with this (I'm also fine with not requiring it ;), but I feel
> like we dropped SQL because lots of folks were already replacing it
> with alternative content [1].  That means folks will no longer have
> time (or as much time) to cover one of the alternative lessons
> (testing, debugging, Make, ???) as they do now, without dropping the SWC
> label.  If we want to pitch a smaller tent, we should have a guess at
> how many potentially SWC-branded workshops will turn into unbranded
> workshops as a result.
> 
> [1]: http://software-carpentry.org/blog/2015/03/and-now-we-are-three.html

Still a strong -1 on separating open science from lessons; if anything, we
should be amping up the integration of our case for (open science habits,
reproducibility, open data, correctness, and efficiency) as part of
(automation, efficiency, good/structured programming habits, and version
control).

We already have the strong suspicion that scientists don't respond well
to being preached at about reproducibility, and so instead we've worked
it into lessons about automation and efficiency.  I would be surprised
if open science were any different than reproducibility in this regard.

**Comment by gvwilson** [comment] 2015-04-08 12:18
I agree it should be integrated with the lesson; how should we handle 
the duplicated material between the Git and Hg lessons?  Copy changes 
manually (small, hopefully infrequent)?

**Comment by wking** [comment] 2015-04-08 16:51
On Wed, Apr 08, 2015 at 05:18:05AM -0700, Greg Wilson wrote:
> I agree it should be integrated with the lesson; …

Maybe my issue here is that the open-science material is currently not
very integrated.  Pulling out the open, licensing, and hosting topics
would be pretty easy and doesn't affect the rest of the Git lesson
(which comes before those topics).  I'm not sure what a tighter
integration would look like though, since the issues are almost
entirely independent of version control within a team.

We could motivate hosting (regardless of the VCS being used) by saying
that it's less work to use external hosting, assuming you're allowed
to use it for your particular project.  But the current hosting topic
covers this angle.  Do we think it's still too preachy?

The open and licensing topics are a bit weaker, because they set you
up for potential later benefits (contributions from others, increased
uptake in your community, something you can point future employers at,
…), but don't have immediate payoffs.  I think these topics may be too
preachy as they currently stand (although the Piwowar paper helps make
the topic more evidence-based), but I don't see much potential for
integrating these ideas more tightly with the VCS-specific topics.

So I'm happy to see tighter integration, but don't see how to move in
that direction.  If we stick with the current level of integration
(independent topics grafted onto the end of the VCS lesson), I still
think we should be pulling them out to a separate repository.

**Closed** 2016-06-15 09:32 UTC
Labels: discussion
