### ISSUE TITLE
Unix shell motivation link broken

### ISSUE THREAD

**Issue by moorepants** [swcarpentry/site#827] opened 2015-02-17 01:52 UTC
One this page:

http://swcarpentry.github.io/shell-novice/

Link:

http://swcarpentry.github.io/shell-novice/motivation.html

**Comment by wking** [comment] 2015-02-17 03:21
On Mon, Feb 16, 2015 at 05:52:33PM -0800, Jason K. Moore wrote:
> One this page:
> 
> http://swcarpentry.github.io/shell-novice/
> 
> Link:
> 
> http://swcarpentry.github.io/shell-novice/motivation.html

Duplicate of swcarpentry/shell-novice#47?

**Comment by r-gaia-cs** [comment] 2015-02-21 01:26
> Duplicate of swcarpentry/shell-novice#47?

Yes. I'm closing this as duplicated.

**Closed by r-gaia-cs** 2015-02-21 01:26 UTC
